.TH MYNTA-QT "1" "January 2026" "Mynta Core" "User Commands"
.SH NAME
mynta-qt \- Mynta Core GUI
.SH SYNOPSIS
.B mynta-qt
[\fIOPTIONS\fR]
.SH DESCRIPTION
.B mynta-qt
is the graphical user interface for Mynta Core.
.PP
Run \fBmynta-qt --help\fR for a full list of options.
.SH OPTIONS
.TP
\fB\-?\fR
Print help message and exit.
.TP
\fB\-version\fR
Print version and exit.
.TP
\fB\-datadir=\fR<dir>
Specify data directory.
.TP
\fB\-conf=\fR<file>
Specify configuration file (default: mynta.conf).
.TP
\fB\-testnet\fR
Use the test network.
.TP
\fB\-regtest\fR
Enter regression test mode.
.TP
\fB\-splash\fR
Show splash screen on startup (default: 1).
.TP
\fB\-min\fR
Start minimized.
.SH "SEE ALSO"
.BR myntad (1),
.BR mynta-cli (1),
.BR mynta-tx (1)
.SH AUTHOR
The Mynta Core developers.
.SH "REPORTING BUGS"
Report bugs at <https://github.com/MyntaProject/Mynta/issues>.
